Script started on Sat Feb  7 19:50:48 2015
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
~
yliu075@hammer $ cs100
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.  Everything you do is being   |
| recorded to measure your progress in the class.                             |
|                                                                             |
| Important commands for the class:                                           |
|   * calcgrade.sh          displays a detailed breakdown of your grade       |
|   * typespeed             practice typing unix commands                     |
|                                                                             |
| Important commands for general C++ programming:                             |
|   * make                  don't call g++ manually; let make do the work!    |
|   * gdb                   the GNU debugger                                  |
|   * valgrind              get rid of your memory leaks                      |
|   * cppcheck              static analysis tool                              |
|   * man                   find help about any syscall / terminal command    |
|                                                                             |
===============================================================================
[0m
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m cppcheck src/ls.cpp
cppcheck: error: could not find or open any of the paths given.
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m cd rshell
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (master) [0;36m$[0m cppcheck src/ls.cpp
Checking src/ls.cpp...
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (master) [0;36m$[0m exit
exit
~
yliu075@hammer $ exit
exit

Script done on Sat Feb  7 19:51:38 2015
