Script started on Sun Mar  8 22:24:23 2015
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
~
yliu075@hammer $ cs100
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.  Everything you do is being   |
| recorded to measure your progress in the class.                             |
|                                                                             |
| Important commands for the class:                                           |
|   * calcgrade.sh          displays a detailed breakdown of your grade       |
|   * typespeed             practice typing unix commands                     |
|                                                                             |
| Important commands for general C++ programming:                             |
|   * make                  don't call g++ manually; let make do the work!    |
|   * gdb                   the GNU debugger                                  |
|   * valgrind              get rid of your memory leaks                      |
|   * cppcheck              static analysis tool                              |
|   * man                   find help about any syscall / terminal command    |
|                                                                             |
===============================================================================
[0m
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m bin   cd rshell
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (master) [0;36m$[0m bin/rshell
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ ls #my rshell rely on PATH
LICENSE  Makefile  README.md  a.out  bin  err.txt  in.txt  out.txt  out2.txt  sig_test	src  test.cpp  tests
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ exit
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (master) [0;36m$[0m old_PATH=$PATH
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (master) [0;36m$[0m PATH=""
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m [0;36m$[0m bin/rshell
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ ls
error in execv: No such file or directory
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ exit
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m [0;36m$[0m #my rshell didn't work because PATH was changed
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m [0;36m$[0m pa  PATH=$old_PATH
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (master) [0;36m$[0m bin/rshell
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ ls
LICENSE  Makefile  README.md  a.out  bin  err.txt  in.txt  out.txt  out2.txt  sig_test	src  test.cpp  tests
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ exit
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (master) [0;36m$[0m #it worked again because I restore the   PATH to its old value
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (master) [0;36m$[0m exit
exit
~
yliu075@hammer $ exit
exit

Script done on Sun Mar  8 22:28:16 2015
