Script started on Sun Mar  8 23:57:22 2015
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
~
yliu075@hammer $ cs100
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.  Everything you do is being   |
| recorded to measure your progress in the class.                             |
|                                                                             |
| Important commands for the class:                                           |
|   * calcgrade.sh          displays a detailed breakdown of your grade       |
|   * typespeed             practice typing unix commands                     |
|                                                                             |
| Important commands for general C++ programming:                             |
|   * make                  don't call g++ manually; let make do the work!    |
|   * gdb                   the GNU debugger                                  |
|   * valgrind              get rid of your memory leaks                      |
|   * cppcheck              static analysis tool                              |
|   * man                   find help about any syscall / terminal command    |
|                                                                             |
===============================================================================
[0m
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m cd rshell
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (master) [0;36m$[0m cd rshell[5Pexitcs100[1Pexitcs100-runtests bin/rshell sig_test 100000exit[Kcs100[1Pexitcd rshell[Kcs100-runtests sig   bin/rshell sig_test 100000
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
************
* sig_test *
************
================================================================================
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ #change dir to src
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ cd src
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ ls
cp.cpp	ls.cpp	main.cpp
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ #chabge dir into non existing dir
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ cd abc
error in chdir: No such file or directory
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ #change dir back to perv dir
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ cd ..
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ ls
LICENSE   README.md  a.script  b.txt  err.txt	in.txt	 out2.txt  src	     tests
Makefile  a.out      b.script  bin    err_test	out.txt  sig_test  test.cpp
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ #cd with other spellings
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ CD src
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ Cd ..
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ cD src
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ #change dir back
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ cd ..
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ #change dir to src with slash at the end
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ cd src/
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ #change dir back
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ cd ..
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ #change dir to src with ./ at the beginning
/home/csmajs/yliu075/rshell
yliu075@hammer.cs.ucr.edu$ cd ./src
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ #change dir with multilple dir chained together
/home/csmajs/yliu075/rshell/src
yliu075@hammer.cs.ucr.edu$ cd ../../../../../
/
yliu075@hammer.cs.ucr.edu$ ls
C:\nppdf32Log\debuglog.txt  cgroup  etc    lib	       media  net   root     srv  usr
bin			    class   extra  lib64       misc   opt   sbin     sys  var
boot			    dev     home   lost+found  mnt    proc  selinux  tmp
/
yliu075@hammer.cs.ucr.edu$ exit

================================================================================
[s%%%%%%%%%%[u[0;32myliu075[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (master) [0;36m$[0m exit
exit
~
yliu075@hammer $ exit
exit

Script done on Sun Mar  8 23:58:03 2015
