Script started on Sun 08 Feb 2015 01:33:01 AM UTC
[01;32myliu075@rshell[00m:[01;34m~/workspace[00m (master) $ exitvalgrind bin/ls
==14110== Memcheck, a memory error detector
==14110== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==14110== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==14110== Command: bin/ls
==14110== 
[39;49mLICENSE                     [39;49mMakefile              [39;49mREADME.md    [39;49m
[39;49mTHIS_IS_A_LONG_FILE_NAME    [94mbin/                  [94msrc/         [39;49m
[92;49mtest*                       [39;49mtest.cpp              [92;49mtest.out*    [39;49m
[94mtests/                      [39;49mtodo                  [92;49mtok.out*     [39;49m
[39;49mtok_test.cpp                [39;49mvalgrind_LS.script    [39;49m
==14110== 
==14110== HEAP SUMMARY:
==14110==     in use at exit: 0 bytes in 0 blocks
==14110==   total heap usage: 54 allocs, 54 frees, 34,876 bytes allocated
==14110== 
==14110== All heap blocks were freed -- no leaks are possible
==14110== 
==14110== For counts of detected and suppressed errors, rerun with: -v
==14110== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
[01;32myliu075@rshell[00m:[01;34m~/workspace[00m (master) $ valgrind bin/lsexit[K
exit

Script done on Sun 08 Feb 2015 01:33:09 AM UTC
