Script started on Sat Feb 21 19:53:02 2015
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
~
yliu075@hammer $ cd rshell
~/rshell
yliu075@hammer $ valgrind bin/rshell
==20898== Memcheck, a memory error detector
==20898== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==20898== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==20898== Command: bin/rshell
==20898== 
yliu075@hammer.cs.ucr.edu$ exit
==20898== 
==20898== HEAP SUMMARY:
==20898==     in use at exit: 29 bytes in 1 blocks
==20898==   total heap usage: 77 allocs, 76 frees, 27,316 bytes allocated
==20898== 
==20898== LEAK SUMMARY:
==20898==    definitely lost: 0 bytes in 0 blocks
==20898==    indirectly lost: 0 bytes in 0 blocks
==20898==      possibly lost: 29 bytes in 1 blocks
==20898==    still reachable: 0 bytes in 0 blocks
==20898==         suppressed: 0 bytes in 0 blocks
==20898== Rerun with --leak-check=full to see details of leaked memory
==20898== 
==20898== For counts of detected and suppressed errors, rerun with: -v
==20898== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 6 from 6)
~/rshell
yliu075@hammer $ exit
exit

Script done on Sat Feb 21 19:53:29 2015
